-- Write SQL queries to perform the following tasks using the Sakila database:
USE sakila;

-- List the number of films per category.
SELECT c.name, COUNT(fc.film_id) AS film_count
FROM category AS c
JOIN film_category AS fc
ON c.category_id = fc.category_id
GROUP BY c.category_id, c.name;

-- Retrieve the store ID, city, and country for each store.
SELECT s.store_id, c.city AS city, co.country AS country
FROM store AS s
JOIN address AS a
ON s.address_id=a.address_id
JOIN city AS c
ON a.city_id=c.city_id
JOIN country AS co
ON c.country_id=co.country_id;

-- Calculate the total revenue generated by each store in dollars.
SELECT c.store_id, SUM(p.amount) AS total_revenue 
FROM customer AS c
JOIN payment AS p
ON c.customer_id = p.customer_id
GROUP BY c.store_id;

-- Determine the average running time of films for each category.
SELECT ca.name, ROUND(AVG(f.length)) AS average_length
FROM category AS ca
JOIN film_category AS fc
ON ca.category_id = fc.category_id
JOIN film AS f
ON fc.film_id=f.film_id
GROUP BY ca.name;